name: CI-macOS

on:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.1.app

      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Clean, build and test
        run: xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
